AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: sam-suburi
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
#=========================
# Parameter
#=========================
Parameters:
  System:
    Type: String
    Default: suburi
    Description: System name
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - prd
      - stg
      - dev
    Description: The environment for which the parameters are created.
  UpdateTokenInterval:
    Type: String
    Default: "10 hours"
Resources:
#=========================
# Parameter Store
#=========================
  # Type: SecureStringは作成不可のため手動で作成する
  # PsCrClientId:
  #   Type: "AWS::SSM::Parameter"
  #   Properties:
  #     Name: !Sub "/${System}/${Environment}/client-id"
  #     Description: "client id for cr. リソース作成後に手動で値を設定する"
  #     Type: "SecureString"
  #     Value: "initVal"
  # PsCrSecret:
  #   Type: "AWS::SSM::Parameter"
  #   Properties:
  #     Name: !Sub "/${System}/${Environment}/secret"
  #     Description: "secret for cr. リソース作成後に手動で値を設定する"
  #     Type: "SecureString"
  #     Value: "initVal"
  TokenParamter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${System}/${Environment}/token
      Description: token for cr. 定期更新する
      Type: String
      Value: initVal
    Metadata:
      SamResourceId: TokenParamter
#=========================
# DynamoDB
#=========================
  ClientDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${System}-${Environment}-client
      AttributeDefinitions:
        - AttributeName: user_name
          AttributeType: S
        - AttributeName: area_id
          AttributeType: S
        - AttributeName: ttl
          AttributeType: N
      KeySchema:
        - AttributeName: user_name
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: TtlIndex
          KeySchema:
            - AttributeName: area_id
              KeyType: HASH
            - AttributeName: ttl
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
#=========================
# Lambda Function
#=========================
  UpdateTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${System}-${Environment}-update-token
      CodeUri: src/lambda/update-token/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TOKEN_PARAM_NAME: !Ref TokenParamter
          CLIENT_ID_PARAM_NAME: !Sub /${System}/${Environment}/client-id
          SECRET_PARAM_NAME: !Sub /${System}/${Environment}/secret
  DynamoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${System}-${Environment}-dynamo
      CodeUri: src/lambda/dynamo/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          CLIENT_TABLE_NAME: !Ref ClientDynamoDBTable
  ClientStreamerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${System}-${Environment}-client-streamer
      Handler: app.handler
      Runtime: nodejs20.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            console.log("Event:", JSON.stringify(event, null, 2));
          };
  NotificationApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${System}-${Environment}-notification-api
      CodeUri: src/lambda/notification-api/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        ApiGet:
          Type: Api
          Properties:
            Path: /items/{itemId}
            Method: GET
            RestApiId: !Ref MyRestApi
            Auth:
              ApiKeyRequired: true
        ApiPost:
          Type: Api
          Properties:
            Path: /news
            Method: POST
            RestApiId: !Ref MyRestApi
            Auth:
              ApiKeyRequired: true
  AppApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${System}-${Environment}-app-api
      CodeUri: src/lambda/app-api/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn
    Environment:
      Variables:
        TOKEN_PARAM_NAME: !Ref TokenParamter
#=========================
# Role
#=========================
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SSMParameterReadWriteAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:PutParameter
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*"
        - PolicyName: KMSDecryptAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*"
        - PolicyName: DynamoDBStreamAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*/stream/*"
        - PolicyName: CloudWatchLogsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*:*"
        - PolicyName: DynamoDBReadWriteAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Scan
                  - dynamodb:Query
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*"
  LambdaSchedulerRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "scheduler.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: InvokeLambda
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "lambda:InvokeFunction"
                Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*"
  ClientStreamerFunctionEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt ClientDynamoDBTable.StreamArn
      FunctionName: !GetAtt ClientStreamerFunction.Arn
      Enabled: true
      BatchSize: 10
      StartingPosition: LATEST
      FilterCriteria:
        Filters:
          - Pattern: |
              {
                "eventName": ["INSERT", "REMOVE"]
              }
#=========================
# Scheduler
#=========================
  UpdateTokenSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      FlexibleTimeWindow:
        Mode: 'OFF'
      ScheduleExpression: !Sub "rate(${UpdateTokenInterval})"
      State: 'DISABLED'
      Target:
        Arn: !GetAtt UpdateTokenFunction.Arn
        RoleArn: !GetAtt LambdaSchedulerRole.Arn
#=========================
# API Gateway
#=========================
  MyRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${System}-${Environment}-api
      StageName: !Sub ${Environment}
      Auth:
        ApiKeyRequired: false
      #  DefaultAuthorizer: MyCognitoAuthorizer # デフォルトを Cognito に設定
        # Authorizers:
        #   MyCognitoAuthorizer:
        #     UserPoolArn: !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPoolId}
  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref MyRestApi
          Stage: !Sub ${Environment}
      UsagePlanName: !Sub ${System}-${Environment}-usage-plan
    DependsOn:
      - MyRestApiStage
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub ${System}-${Environment}-api-key
      Enabled: true
      StageKeys:
        - RestApiId: !Ref MyRestApi
          StageName: !Sub ${Environment}
    DependsOn:
      - MyRestApiStage
  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyType: API_KEY
      KeyId: !Ref ApiKey
      UsagePlanId: !Ref UsagePlan
